//! Bash-specific shell completion enhancements
//! 
//! This module provides custom Bash completion functions that enhance
//! the basic completions generated by clap_complete with dynamic,
//! cache-based substance and route completions.

use std::io::Write;

/// Write custom Bash completion functions that provide dynamic completions
/// 
/// These functions are appended to the basic clap-generated completions and provide:
/// - Dynamic substance name completion from cache
/// - Route of administration completion from cache  
/// - Automatic cache refresh when stale
/// - Integration with the standard Bash completion system
pub fn write_custom_completions<W: Write>(buf: &mut W) -> std::io::Result<()> {
    writeln!(buf, r#"
# Custom completion function for substance names
_neuronek_substance_names() {{
    local substances cache_file
    cache_file="$HOME/.cache/neuronek/completions/substances"
    
    # Check if cache is stale (older than 5 minutes) and refresh in background
    if [[ ! -f "$cache_file" ]] || [[ $(find "$cache_file" -mmin +5 2>/dev/null) ]]; then
        neuronek completion cache refresh-cache >/dev/null 2>&1 &
    fi
    
    # Use cached values for immediate completion
    substances=$(neuronek completion cache get-cached substances 2>/dev/null)
    if [[ -n "$substances" ]]; then
        COMPREPLY=($(compgen -W "$substances" -- "${{COMP_WORDS[COMP_CWORD]}}"))
    fi
}}

# Custom completion function for route names
_neuronek_route_names() {{
    local routes
    routes=$(neuronek completion cache get-cached routes 2>/dev/null)
    if [[ -n "$routes" ]]; then
        COMPREPLY=($(compgen -W "$routes" -- "${{COMP_WORDS[COMP_CWORD]}}"))
    fi
}}

# Custom completion function for ingestion IDs
_neuronek_ingestion_ids() {{
    local ingestions
    # Get the last 20 ingestion IDs
    ingestions=$(neuronek ingestion list --limit 20 --format json 2>/dev/null | jq -r '.[].id' 2>/dev/null)
    if [[ -n "$ingestions" ]]; then
        COMPREPLY=($(compgen -W "$ingestions" -- "${{COMP_WORDS[COMP_CWORD]}}"))
    fi
}}

# Override completion for ingestion log --substance and --roa
_neuronek_ingestion_log_completion() {{
    case "${{COMP_WORDS[COMP_CWORD-1]}}" in
        -s|--substance)
            _neuronek_substance_names
            return 0
            ;;
        -r|--roa)
            _neuronek_route_names
            return 0
            ;;
    esac
    return 1
}}

# Override completion for ingestion update
_neuronek_ingestion_update_completion() {{
    local cmd_index=2  # Position where "update" appears
    
    # Check if we're completing the ID argument (first positional after "update")
    if [[ $COMP_CWORD -eq $((cmd_index + 1)) ]] && [[ "${{COMP_WORDS[cmd_index]}}" == "update" ]]; then
        _neuronek_ingestion_ids
        return 0
    fi
    
    # Check for option arguments
    case "${{COMP_WORDS[COMP_CWORD-1]}}" in
        -n|--name)
            _neuronek_substance_names
            return 0
            ;;
        -r|--roa)
            _neuronek_route_names
            return 0
            ;;
    esac
    return 1
}}

# Override completion for ingestion delete/view
_neuronek_ingestion_id_completion() {{
    local cmd_index=2  # Position where command appears
    
    # Check if we're completing the ID argument (first positional)
    if [[ $COMP_CWORD -eq $((cmd_index + 1)) ]]; then
        _neuronek_ingestion_ids
        return 0
    fi
    return 1
}}

# Hook into the main completion function
_neuronek_dynamic() {{
    local cmd="${{COMP_WORDS[1]}}"
    local subcmd="${{COMP_WORDS[2]}}"
    
    # Handle ingestion subcommands
    if [[ "$cmd" == "ingestion" ]]; then
        case "$subcmd" in
            log|create|add|make|new|mk)
                if _neuronek_ingestion_log_completion; then
                    return 0
                fi
                ;;
            update|edit)
                if _neuronek_ingestion_update_completion; then
                    return 0
                fi
                ;;
            delete|rm|del|remove)
                if _neuronek_ingestion_id_completion; then
                    return 0
                fi
                ;;
            view|show|display|info)
                if _neuronek_ingestion_id_completion; then
                    return 0
                fi
                ;;
        esac
    fi
    
    # Fall back to default completion
    _neuronek
}}

# Replace the default completion with our enhanced version
complete -F _neuronek_dynamic -o nosort -o bashdefault -o default neuronek
"#)
}