//! Fish-specific shell completion enhancements
//! 
//! This module provides custom Fish completion functions that enhance
//! the basic completions generated by clap_complete with dynamic,
//! cache-based substance and route completions.

use std::io::Write;

/// Write custom Fish completion functions that provide dynamic completions
/// 
/// These functions are appended to the basic clap-generated completions and provide:
/// - Dynamic substance name completion from cache
/// - Route of administration completion from cache
/// - Automatic cache refresh when stale
/// - Ingestion ID completion with descriptions
/// - Integration with Fish's powerful completion system
pub fn write_custom_completions<W: Write>(buf: &mut W) -> std::io::Result<()> {
    writeln!(buf, r#"
# Check and refresh cache if needed
function __neuronek_check_cache
    set cache_file "$HOME/.cache/neuronek/completions/substances"
    if not test -f "$cache_file"; or test (find "$cache_file" -mmin +5 2>/dev/null)
        neuronek completion cache refresh-cache >/dev/null 2>&1 &
    end
end

# Custom completion function for substance names
function __neuronek_substance_names
    __neuronek_check_cache
    neuronek completion cache get-cached substances 2>/dev/null
end

# Custom completion function for route names
function __neuronek_route_names
    neuronek completion cache get-cached routes 2>/dev/null
end

# Custom completion function for ingestion IDs with descriptions
function __neuronek_ingestion_ids
    # Get recent ingestions with details
    set -l ingestions (neuronek ingestion list --limit 20 --format json 2>/dev/null)
    if test -n "$ingestions"
        # Parse JSON to show ID with description
        echo "$ingestions" | jq -r '.[] | "\(.id)\t\(.ingestion_date | split("T")[0]) \(.substance_name) \(.dosage)mg"' 2>/dev/null
    end
end

# Add dynamic completions for ingestion log command
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from log" -s s -l substance -xa "(__neuronek_substance_names)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from log" -s r -l roa -xa "(__neuronek_route_names)"

# Add dynamic completions for ingestion log command aliases
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from create" -s s -l substance -xa "(__neuronek_substance_names)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from create" -s r -l roa -xa "(__neuronek_route_names)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from add" -s s -l substance -xa "(__neuronek_substance_names)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from add" -s r -l roa -xa "(__neuronek_route_names)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from make" -s s -l substance -xa "(__neuronek_substance_names)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from make" -s r -l roa -xa "(__neuronek_route_names)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from new" -s s -l substance -xa "(__neuronek_substance_names)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from new" -s r -l roa -xa "(__neuronek_route_names)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from mk" -s s -l substance -xa "(__neuronek_substance_names)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from mk" -s r -l roa -xa "(__neuronek_route_names)"

# Add dynamic completions for ingestion update command
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from update" -xa "(__neuronek_ingestion_ids)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from update" -s n -l name -xa "(__neuronek_substance_names)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from update" -s r -l roa -xa "(__neuronek_route_names)"

# Add dynamic completions for ingestion update alias (edit)
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from edit" -xa "(__neuronek_ingestion_ids)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from edit" -s n -l name -xa "(__neuronek_substance_names)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from edit" -s r -l roa -xa "(__neuronek_route_names)"

# Add dynamic completions for ingestion delete command and aliases
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from delete" -xa "(__neuronek_ingestion_ids)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from rm; and not __fish_seen_subcommand_from rm" -xa "(__neuronek_ingestion_ids)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from del; and not __fish_seen_subcommand_from del" -xa "(__neuronek_ingestion_ids)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from remove" -xa "(__neuronek_ingestion_ids)"

# Add dynamic completions for ingestion view command and aliases
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from view; and not __fish_seen_subcommand_from view" -xa "(__neuronek_ingestion_ids)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from show; and not __fish_seen_subcommand_from show" -xa "(__neuronek_ingestion_ids)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from display; and not __fish_seen_subcommand_from display" -xa "(__neuronek_ingestion_ids)"
complete -c neuronek -n "__fish_seen_subcommand_from ingestion; and __fish_seen_subcommand_from info; and not __fish_seen_subcommand_from info" -xa "(__neuronek_ingestion_ids)"

# Add dynamic completions for substance get command
complete -c neuronek -n "__fish_seen_subcommand_from substance; and __fish_seen_subcommand_from get" -xa "(__neuronek_substance_names)"
"#)
}