cargo-features = ["edition2024", "codegen-backend"]

[package]
name = "neuronek"
description = "🧬 Intelligent dosage tracker application for monitoring supplements, nootropics and psychoactive substances along with their long-term influence on one's mind and body."
authors = ["Jakub Olan <keinsell@protonmail.com>"]
version = "0.0.1-alpha.6"
edition = "2024"
repository = "https://github.com/keinsell/neuronek"
homepage = "https://github.com/keinsell/neuronek"
license-file = "LICENSE"

[[bin]]
name = "neuronek"
path = "src/main.rs"

[package.metadata.wix]
upgrade-guid = "82B4BD62-1152-44E6-B4FA-879648018D6F"
path-guid = "8EB7202C-B16A-4E75-900B-8924E701FA76"
license = false
eula = false

[profile.release]
codegen-units = 1
lto = "fat"
strip = true
opt-level = 3
panic = "abort"

[features]
default = ["command_line", "telemetry"]
command_line = []
terminal = []
telemetry = ["sentry-tracing/default"]
#web = ["dioxus/web"]
#desktop = ["dioxus/desktop"]
#mobile = ["dioxus/mobile"]
#server = ["dioxus/server"]


[dependencies]
#dioxus = { version = "0.6.0", features = ["router", "fullstack", "launch"] }
comfy-table = "7.1.4"
async-std = { version = "1.12.0", features = ["attributes", "async-global-executor", "async-process"] }
atty = "0.2.14"
chrono = { version = "0.4", features = ["serde"] }
chrono-english = "0.1.7"
clap = { version = "4.5.23", features = ["derive", "wrap_help", "suggestions", "std", "cargo"] }
clap-verbosity-flag = "3.0.1"
crossterm = "0.27.0"
date_time_parser = "0.2.0"
delegate = "0.13.1"
derivative = "2.2.0"
directories = { version = "5.0.1" }
float-pretty-print = "0.1.1"
futures = { version = "0.3.31", features = ["futures-executor", "thread-pool"] }
hashbrown = { version = "0.15.2", features = ["serde"] }
iso8601-duration = "0.2.0"
lazy_static = "1.5.0"
measurements = { version = "0.11.0", features = ["std", "serde", "from_str", "regex"] }
miette = { version = "7.4.0", features = ["fancy", "serde", "syntect-highlighter", "derive"] }
pubchem = "0.1.1"
ratatui = "0.26.1"
rust-embed = "8.2.0"
sea-orm = { version = "1.1.2", features = ["sqlx-sqlite", "runtime-async-std-rustls", "serde_json", "with-chrono"] }
serde = { version = "1.0.216", features = ["derive", "std", "unstable", "rc", "serde_derive"] }
tabled = { version = "0.18", features = ["std", "macros", "ansi", "derive", "tabled_derive"] }
sea-orm-migration = { version = "1.1.0", features = [
    "sqlx-sqlite",
    "runtime-async-std-rustls"
] }
serde_json = "1.0.134"
owo-colors = "4.1.0"
chrono-humanize = "0.2.3"
async-trait = "0.1.85"
indicatif = "0.17.9"
tracing-subscriber = "0.3.18"
tracing-indicatif = "0.3.8"
tracing = "0.1.40"
thiserror = "2.0.11"
cached = { version = "0.54.0", features = ["disk_store", "async"] }
derive_more = { version = "2.0.1", features = ["full"] }
strum = "0.27.0"
human-panic = "2.0.2"
uuid = { version = "1.12.1", features = ["v4"] }
etcetera = "0.8.0"
tracing-appender = "0.2.3"
textplots = "0.8.6"
valuable = { version = "0.1.1", features = ["derive"] }
derive = "1.0.0"
tuirealm = { version = "2.1.0", features = ["derive", "crossterm"] }
bon = "3.3.2"
termimad = "0.31.2"
humantime = "2.1.0"
nutype = { version = "0.6.1", features = ["arbitrary", "new_unchecked", "serde"] }
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"
once_cell = "1.20.3"
minimo = "0.1.0"
supports-color = "3.0.2"
derive-new = "0.7.0"
strum_macros = "0.27.1"
json_to_table = "0.10.0"
o2o = { version = "0.5.3", features = ["o2o-macros", "o2o-impl"] }
clap_complete = "4.5.46"
tokio = { version = "1.0", features = ["rt", "rt-multi-thread"] }
tempfile = "3.16.0"
assert_cmd = "2.0.16"
sentry = "0.36.0"
sentry-tracing = "0.36.0"
promkit = "0.8.0"
dialoguer = "0.11.0"
ctor = "0.4.1"

[profile]
[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

[profile.dist]
inherits = "release"
lto = "fat"

[dev-dependencies]
predicates = "3.1.3"
