module.exports = {
  $schema: "http://json.schemastore.org/prettierrc",
  trailingComma: "all",
  tabWidth: 2,
  useTabs: false,
  semi: false,
  singleQuote: true,
  printWidth: 120,
  quoteProps: "consistent",
  jsxSingleQuote: true,
  bracketSpacing: true,
  jsxBracketSameLine: true,
  bracketSameLine: true,
  arrowParens: "always",
  proseWrap: "always",
  htmlWhitespaceSensitivity: "css",
  endOfLine: "lf",
};
