//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10


use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "formulation")]
pub struct Model
{
	#[sea_orm(primary_key)]
	pub id: i32,
	#[sea_orm(column_type = "Text", unique)]
	pub name: String,
	#[sea_orm(column_type = "Text", nullable)]
	pub summary: Option<String>,
	#[sea_orm(column_type = "Text", nullable)]
	pub labeller: Option<String>,
	#[sea_orm(column_type = "Text", nullable)]
	pub form: Option<String>,
	#[sea_orm(column_type = "Text")]
	pub route: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation
{
	#[sea_orm(has_many = "super::formulation_ingredient::Entity")]
	FormulationIngredient,
}

impl Related<super::formulation_ingredient::Entity> for Entity
{
	fn to() -> RelationDef { Relation::FormulationIngredient.def() }
}

impl ActiveModelBehavior for ActiveModel {}
