//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8


use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "formulation_ingredient")]
pub struct Model
{
	#[sea_orm(primary_key)]
	pub id: i32,
	pub formulation_id: i32,
	#[sea_orm(column_type = "Text")]
	pub substance_name: String,
	pub dosage: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation
{
	#[sea_orm(
		belongs_to = "super::formulation::Entity",
		from = "Column::FormulationId",
		to = "super::formulation::Column::Id",
		on_update = "Cascade",
		on_delete = "Cascade"
	)]
	Formulation,
}

impl Related<super::formulation::Entity> for Entity
{
	fn to() -> RelationDef { Relation::Formulation.def() }
}

impl ActiveModelBehavior for ActiveModel {}
