//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10


use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ingestion_group")]
pub struct Model
{
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text", unique)]
	pub id: String,
	#[sea_orm(column_type = "Text")]
	pub name: String,
	#[sea_orm(column_type = "Text")]
	pub created_at: String,
	#[sea_orm(column_type = "Text")]
	pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation
{
	#[sea_orm(has_many = "super::ingestion_group_ingestion::Entity")]
	IngestionGroupIngestion,
}

impl Related<super::ingestion_group_ingestion::Entity> for Entity
{
	fn to() -> RelationDef { Relation::IngestionGroupIngestion.def() }
}

impl ActiveModelBehavior for ActiveModel {}
