//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8


use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ingestion_group_ingestion")]
pub struct Model
{
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub id: String,
	#[sea_orm(column_type = "Text")]
	pub group_id: String,
	pub ingestion_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation
{
	#[sea_orm(
		belongs_to = "super::ingestion::Entity",
		from = "Column::IngestionId",
		to = "super::ingestion::Column::Id",
		on_update = "Cascade",
		on_delete = "Cascade"
	)]
	Ingestion,
	#[sea_orm(
		belongs_to = "super::ingestion_group::Entity",
		from = "Column::GroupId",
		to = "super::ingestion_group::Column::Id",
		on_update = "Cascade",
		on_delete = "Cascade"
	)]
	IngestionGroup,
}

impl Related<super::ingestion::Entity> for Entity
{
	fn to() -> RelationDef { Relation::Ingestion.def() }
}

impl Related<super::ingestion_group::Entity> for Entity
{
	fn to() -> RelationDef { Relation::IngestionGroup.def() }
}

impl ActiveModelBehavior for ActiveModel {}
