//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7


use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ingestion")]
pub struct Model
{
	#[sea_orm(primary_key)]
	pub id: i32,
	pub substance_name: String,
	pub route_of_administration: String,
	#[sea_orm(column_type = "Float")]
	pub dosage: f32,
	pub ingested_at: DateTime,
	pub updated_at: DateTime,
	pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation
{
	#[sea_orm(has_many = "super::ingestion_group_ingestion::Entity")]
	IngestionGroupIngestion,
	#[sea_orm(has_many = "super::ingestion_phase::Entity")]
	IngestionPhase,
}

impl Related<super::ingestion_group_ingestion::Entity> for Entity
{
	fn to() -> RelationDef { Relation::IngestionGroupIngestion.def() }
}

impl Related<super::ingestion_phase::Entity> for Entity
{
	fn to() -> RelationDef { Relation::IngestionPhase.def() }
}

impl ActiveModelBehavior for ActiveModel {}
