//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10


use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ingestion_phase")]
pub struct Model
{
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text", unique)]
	pub id: String,
	pub ingestion_id: i32,
	#[sea_orm(column_type = "Text")]
	pub classification: String,
	pub start_date_min: DateTime,
	pub start_date_max: DateTime,
	pub end_date_min: DateTime,
	pub end_date_max: DateTime,
	pub weight: Decimal,
	#[sea_orm(column_type = "Text")]
	pub duration_min: String,
	#[sea_orm(column_type = "Text")]
	pub duration_max: String,
	#[sea_orm(column_type = "Text")]
	pub substance_name: String,
	#[sea_orm(column_type = "Text")]
	pub created_at: String,
	#[sea_orm(column_type = "Text")]
	pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation
{
	#[sea_orm(
		belongs_to = "super::ingestion::Entity",
		from = "Column::IngestionId",
		to = "super::ingestion::Column::Id",
		on_update = "Cascade",
		on_delete = "Cascade"
	)]
	Ingestion,
}

impl Related<super::ingestion::Entity> for Entity
{
	fn to() -> RelationDef { Relation::Ingestion.def() }
}

impl ActiveModelBehavior for ActiveModel {}
