//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub mod prelude;

pub mod formulation;
pub mod formulation_ingredient;
pub mod ingestion;
pub mod ingestion_group;
pub mod ingestion_group_ingestion;
pub mod ingestion_phase;
pub mod substance;
pub mod substance_route_of_administration;
pub mod substance_route_of_administration_dosage;
pub mod substance_route_of_administration_phase;
