//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

pub use super::ingestion::Entity as Ingestion;
pub use super::ingestion_phase::Entity as IngestionPhase;
pub use super::substance::Entity as Substance;
pub use super::substance_route_of_administration::Entity as SubstanceRouteOfAdministration;
pub use super::substance_route_of_administration_dosage::Entity as SubstanceRouteOfAdministrationDosage;
pub use super::substance_route_of_administration_phase::Entity as SubstanceRouteOfAdministrationPhase;
