//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub use super::formulation::Entity as Formulation;
pub use super::formulation_ingredient::Entity as FormulationIngredient;
pub use super::ingestion::Entity as Ingestion;
pub use super::ingestion_group::Entity as IngestionGroup;
pub use super::ingestion_group_ingestion::Entity as IngestionGroupIngestion;
pub use super::ingestion_phase::Entity as IngestionPhase;
pub use super::substance::Entity as Substance;
pub use super::substance_route_of_administration::Entity as SubstanceRouteOfAdministration;
pub use super::substance_route_of_administration_dosage::Entity as SubstanceRouteOfAdministrationDosage;
pub use super::substance_route_of_administration_phase::Entity as SubstanceRouteOfAdministrationPhase;
