//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10


use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "substance")]
pub struct Model
{
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text", unique)]
	pub id: String,
	#[sea_orm(column_type = "Text", unique)]
	pub name: String,
	#[sea_orm(column_type = "Text")]
	pub common_names: String,
	#[sea_orm(unique)]
	pub pubchem_cid: i32,
	#[sea_orm(column_type = "Text", nullable)]
	pub psychonautwiki_url: Option<String>,
	#[sea_orm(column_type = "Text")]
	pub psychoactive_class: String,
	#[sea_orm(column_type = "Text", nullable)]
	pub chemical_class: Option<String>,
	#[sea_orm(column_type = "Text", nullable)]
	pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation
{
	#[sea_orm(has_many = "super::substance_route_of_administration::Entity")]
	SubstanceRouteOfAdministration,
}

impl Related<super::substance_route_of_administration::Entity> for Entity
{
	fn to() -> RelationDef { Relation::SubstanceRouteOfAdministration.def() }
}

impl ActiveModelBehavior for ActiveModel {}
