//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "substance_route_of_administration")]
pub struct Model
{
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub id: String,
	#[sea_orm(column_name = "substanceName", column_type = "Text")]
	pub substance_name: String,
	#[sea_orm(column_type = "Text")]
	pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation
{
	#[sea_orm(
		belongs_to = "super::substance::Entity",
		from = "Column::SubstanceName",
		to = "super::substance::Column::Name",
		on_update = "Cascade",
		on_delete = "Restrict"
	)]
	Substance,
	#[sea_orm(has_many = "super::substance_route_of_administration_dosage::Entity")]
	SubstanceRouteOfAdministrationDosage,
	#[sea_orm(has_many = "super::substance_route_of_administration_phase::Entity")]
	SubstanceRouteOfAdministrationPhase,
}

impl Related<super::substance::Entity> for Entity
{
	fn to() -> RelationDef { Relation::Substance.def() }
}

impl Related<super::substance_route_of_administration_dosage::Entity> for Entity
{
	fn to() -> RelationDef { Relation::SubstanceRouteOfAdministrationDosage.def() }
}

impl Related<super::substance_route_of_administration_phase::Entity> for Entity
{
	fn to() -> RelationDef { Relation::SubstanceRouteOfAdministrationPhase.def() }
}

impl ActiveModelBehavior for ActiveModel {}
