name: CI

on:
  pull_request:
    branches:
      - main
      - next
      - trunk
      - release/*
      - feature/*
      - bugfix/*
      - hotfix/*
      - chore/*
  push:
    branches:
      - next
      - main
      - trunk
      - release/*
      - feature/*
      - bugfix/*
      - hotfix/*
      - chore/*
  release:
    types:
      - released
      - prereleased

jobs:
  lint:
    name: "lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          override: true
          components: rustfmt, clippy
      - name: Run rustfmt
        run: cargo fmt --all -- --check
        continue-on-error: true
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        continue-on-error: true

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true

      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/ # Cache the build target directory
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.target }}-

      - name: Cargo test
        run: cargo nextest run --workspace --all-targets --all-features --no-tests=pass

      - name: Build application
        run: cargo build --release --target ${{ matrix.target }}

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: neuronek-cli-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/neuronek
            target/${{ matrix.target }}/release/neuronek.exe
          if-no-files-found: error

  nix_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: build
        run: nix build
      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: nix-build-result
          path: ./result
